# Generated by Django 3.2.6 on 2021-09-15 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(default='', max_length=30)),
                ('buyer_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30)),
                ('order_number', models.CharField(default='', max_length=30)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid')], default='Created', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BotListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(default='', max_length=25)),
                ('img_url', models.CharField(default='', max_length=100)),
                ('key', models.CharField(default='', max_length=200)),
                ('key_nickname', models.CharField(default='', max_length=200)),
                ('listing_type', models.CharField(default='', max_length=30)),
                ('start_time', models.CharField(default='', max_length=200)),
                ('end_time', models.CharField(default='', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Show', 'Show'), ('Unshow', 'Unshow')], default='Show', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('website', models.CharField(default='', max_length=100)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('img_url', models.CharField(default='', max_length=100)),
                ('features', models.ManyToManyField(to='bots.FeaturesType')),
                ('systems', models.ManyToManyField(to='bots.SystemType')),
            ],
        ),
    ]
