# Generated by Django 3.2.6 on 2021-09-15 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlisting',
            name='user',
        ),
        migrations.AddField(
            model_name='botlisting',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
