# Generated by Django 3.2.6 on 2021-09-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20210915_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botlisting',
            name='user',
        ),
        migrations.AddField(
            model_name='botlisting',
            name='user',
            field=models.CharField(default='', max_length=25),
        ),
    ]
