# Generated by Django 3.2.6 on 2021-09-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20210915_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlisting',
            name='user_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botlisting',
            name='user_refs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botlisting',
            name='user_sellingnum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botlisting',
            name='user_timezone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
