# Generated by Django 3.2.6 on 2021-09-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_botbidding_deposit_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botbidding',
            name='deposit_order_no',
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='payment_status',
            field=models.CharField(choices=[('Listing', 'Listing'), ('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Listing', max_length=15),
        ),
    ]
