# Generated by Django 3.2.6 on 2021-09-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_listorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidorder',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bidorder',
            name='key_nickname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listorder',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listorder',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
