# Generated by Django 3.2.6 on 2021-09-17 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_auto_20210917_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbidding',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='botbidding',
            name='key_nickname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 15, 25, 24, 631798)),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 15, 25, 24, 631798)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 15, 25, 24, 630805)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 15, 25, 24, 630805)),
        ),
    ]
