# Generated by Django 3.2.6 on 2021-09-19 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0022_auto_20210918_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 22, 13, 2, 327967)),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 22, 13, 2, 327967)),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Processing', 'Processing')], default='Unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 22, 13, 2, 325971)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 22, 13, 2, 325971)),
        ),
    ]
