# Generated by Django 3.2.6 on 2021-09-20 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0028_auto_20210919_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlisting',
            name='keyreset_status',
            field=models.CharField(choices=[('Waiting for reset', 'Waiting for reset'), ('Nothing', 'Nothing')], default='Nothing', max_length=30),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 16, 56, 301330)),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 16, 56, 301330)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 16, 56, 300334)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 16, 56, 300334)),
        ),
    ]
