# Generated by Django 3.2.6 on 2021-09-29 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0038_auto_20210928_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botlisting',
            old_name='price',
            new_name='rmb_price',
        ),
        migrations.AddField(
            model_name='botlisting',
            name='usd_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 122259)),
        ),
        migrations.AlterField(
            model_name='bidorder',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 122259)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 121259)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 121259)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='remove_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 121259)),
        ),
        migrations.AlterField(
            model_name='botbidding',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 121259), max_length=200),
        ),
        migrations.AlterField(
            model_name='botlisting',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 120263)),
        ),
        migrations.AlterField(
            model_name='botlisting',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 120263), max_length=200),
        ),
    ]
