# Generated by Django 3.2.6 on 2021-09-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20)),
                ('order_id', models.CharField(default='', max_length=20)),
                ('use_points', models.FloatField(default=0.0)),
                ('use_balance', models.FloatField(default=0.0)),
                ('payment_status', models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid')], default='', max_length=20)),
                ('listing', models.ManyToManyField(default='', to='bots.BotListing')),
            ],
        ),
    ]
