# Generated by Django 3.2.6 on 2021-09-16 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_itemincart_bidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemincart',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='itemincart',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='itemincart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='itemincart',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
