# Generated by Django 3.2.6 on 2021-09-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20)),
                ('amount', models.FloatField(default=0.0)),
                ('use', models.CharField(choices=[('topup', 'topup'), ('withdrawal', 'withdrawal')], default='', max_length=20)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Processing', 'Processing')], default='', max_length=20)),
            ],
        ),
    ]
