# Generated by Django 3.2.6 on 2021-09-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bidding_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
