# Generated by Django 3.2.6 on 2021-09-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rental_bidding_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='alipay_no',
            field=models.CharField(default='', max_length=30),
        ),
    ]
