# Generated by Django 3.2.6 on 2021-09-19 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_transaction_alipay_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 22, 17, 15, 392665)),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_from',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Bid', 'Bid')], default='', max_length=30),
        ),
    ]
