# Generated by Django 3.2.6 on 2021-09-20 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210919_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 9, 16, 56, 295347)),
        ),
    ]
