# Generated by Django 3.2.6 on 2021-09-21 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_rental_keyreset_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 21, 11, 51, 0, 581587), max_length=200),
        ),
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 11, 51, 0, 581587)),
        ),
    ]
