# Generated by Django 3.2.6 on 2021-09-21 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210921_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 13, 15, 7, 702877)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 21, 13, 15, 7, 702877), max_length=200),
        ),
    ]
