# Generated by Django 3.2.6 on 2021-09-21 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210921_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='alipay_id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='alipay_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 21, 57, 26, 314531)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 21, 21, 57, 26, 314531), max_length=200),
        ),
    ]
