# Generated by Django 3.2.6 on 2021-09-21 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210921_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='alipay_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 22, 6, 31, 990777)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 21, 22, 6, 31, 990777), max_length=200),
        ),
    ]
