# Generated by Django 3.2.6 on 2021-09-23 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210921_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discordavatar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 22, 55, 11, 149578)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 23, 22, 55, 11, 149578), max_length=200),
        ),
    ]
