# Generated by Django 3.2.6 on 2021-09-28 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210923_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinventory',
            name='img_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('GMT+8', 'GMT+8'), ('GMT-4', 'GMT-4'), ('GMT+1', 'GMT+1')], default='GMT+8', max_length=15),
        ),
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 17, 55, 51, 969438)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 28, 17, 55, 51, 969438), max_length=200),
        ),
    ]
