# Generated by Django 3.2.6 on 2021-09-29 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210928_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 116274)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 10, 56, 21, 116274), max_length=200),
        ),
    ]
