# Generated by Django 3.2.6 on 2021-10-01 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210929_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botinventory',
            name='key',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='rental',
            name='keyreset_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 11, 40, 37, 808338)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='request_time',
            field=models.CharField(default=datetime.datetime(2021, 10, 1, 11, 40, 37, 808338), max_length=200),
        ),
    ]
